DESCRIBE EMP;

--1
SELECT HIREDATE AS FEHCA FROM EMP ORDER BY 1;
--2
SELECT EMPNO,ENAME,SAL*1.15 AS "SALRIO 2" FROM EMP ;
--3
SELECT EMPNO,ENAME,SAL*1.15 AS "SALARIO 2",((SAL*1.15)-SAL) AS "SALARIO 3" FROM EMP;
--4
SELECT ENAME,HIREDATE,ADD_MONTHS(HIREDATE,6) AS "FECHA REVISION" FROM EMP;
--5
SELECT ENAME,CEIL((MONTHS_BETWEEN(SYSDATE,HIREDATE))) AS "MESES" FROM EMP ORDER BY MESES DESC;
--6
SELECT ENAME || ' GANA ' || SAL || ' MENSUALMENTE PERO QUIERE' || '3 VECES MAS ' || SAL*3 FROM EMP;  //Frase personalizada concatena// 1 columna resultante
--7
SELECT ENAME,LPAD(TO_CHAR(SAL), 15, '$') AS "SALARIO FORMATEADO" FROM EMP ;//OPERA SOBRE CADENAS CAMBIAMOS SAL TIPO NUMBER A CHAR SI TE DA ERROR
--8
SELECT INITCAP(ENAME)||LENGTH(ENAME)FROM EMP WHERE ENAME LIKE 'J%' OR ENAME LIKE 'A%' OR ENAME LIKE 'M%'; //LIKE FILTRO POR CARACTER