DESCRIBE EMP;
--1
SELECT ENAME,SAL FROM EMP;
--2
SELECT ENAME,DEPTNO FROM EMP WHERE EMPNO=7566;
--3
SELECT ENAME,SAL FROM EMP WHERE SAL NOT BETWEEN 1500 AND 2850;
--4
SELECT ENAME,JOB,HIREDATE FROM EMP WHERE HIREDATE BETWEEN TO_DATE('20-FEB-1981','DD-MON-YYYY') AND TO_DATE('01-MAY-1981','DD-MON-YYYY')ORDER BY HIREDATE ASC;
--5
SELECT ENAME,DEPTNO 
FROM EMP
WHERE DEPTNO in (10,30) ORDER BY 1;
--6
SELECT ENAME AS "EMPLEADO",SAL AS "SUELDO MENSUAL" FROM EMP WHERE DEPTNO IN(10,30) AND SAL>1500;
--7
SELECT ENAME,HIREDATE FROM EMP WHERE HIREDATE BETWEEN DATE '1982-01-01' AND DATE '1982-12-31';
--8
SELECT ENAME,JOB FROM EMP WHERE MGR IS NULL;
--9?
SELECT ENAME,SAL,COMM FROM EMP WHERE COMM > 0 ORDER BY SAL DESC , COMM DESC;
--10
SELECT ENAME FROM EMP WHERE ENAME LIKE '__A%';
--11
SELECT ENAME FROM EMP WHERE (ENAME LIKE '%L%L%' AND DEPTNO=30 )OR MGR= 7782;
--12
SELECT ENAME,JOB,SAL FROM EMP WHERE JOB IN ('CLERK','ANALYST');
--13
SELECT ENAME,SAL,COMM FROM EMP WHERE COMM>SAL*1.10;//1+porcentaje en decimal para aumenter si es resta 1-porcentaje

