/
CREATE OR REPLACE VIEW V_EMP_DEPT
AS
SELECT E.EMPNO,E.ENAME,D.DNAME,E.SAL,E.HIREDATE,D.LOC
FROM EMP E
INNER JOIN DEPT D ON E.DEPTNO=D.DEPTNO;


/
CREATE OR REPLACE TRIGGER TG_INSERT_EMP_DEPT
INSTEAD OF INSERT ON V_EMP_DEPT
FOR EACH ROW
DECLARE
  v_mgr_empno EMP.EMPNO%TYPE;
  v_deptno DEPT.DEPTNO%TYPE;
BEGIN
  -- 1. Buscar EMPNO del jefe KING
  SELECT EMPNO INTO v_mgr_empno
  FROM EMP
  WHERE UPPER(ENAME) = 'KING';

  -- 2. Buscar si existe el departamento
  BEGIN
    SELECT DEPTNO INTO v_deptno
    FROM DEPT
    WHERE DNAME = :NEW.DNAME;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      -- Si no existe, crear el departamento con ID nuevo
      SELECT MAX(DEPTNO) + 10 INTO v_deptno FROM DEPT;

      INSERT INTO DEPT(DEPTNO, DNAME, LOC)
      VALUES (v_deptno, :NEW.DNAME, :NEW.LOC);
  END;

  -- 3. Insertar nuevo empleado con el jefe KING
  INSERT INTO EMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, DEPTNO)
  VALUES (:NEW.EMPNO, :NEW.ENAME, 'CLERK', v_mgr_empno, :NEW.HIREDATE, :NEW.SAL, v_deptno);
END;
/
/*probar a insertar CUALQUIERA*/
SELECT * FROM V_EMP_DEPT;
INSERT INTO V_EMP_DEPT (EMPNO, ENAME, DNAME, SAL, HIREDATE, LOC)
VALUES (9999, 'NUEVO1', 'SALES', 1500, SYSDATE, 'CHICAGO');

INSERT INTO V_EMP_DEPT (EMPNO, ENAME, DNAME, SAL, HIREDATE, LOC)
VALUES (9998, 'NUEVO2', 'MARKETING', 1800, SYSDATE, 'SEVILLA');

ROLLBACK;

/*3*/
CREATE OR REPLACE TRIGGER TG_DELETE_EMP_DEPT
INSTEAD OF DELETE ON V_EMP_DEPT
FOR EACH ROW
BEGIN
  DELETE FROM EMP WHERE EMPNO = :OLD.EMPNO;
END;
/
/*PROBAR A VER SI BORRA*/
DELETE FROM V_EMP_DEPT WHERE EMPNO = 9999;
