--1
SELECT cname, email
FROM CUSTOMERS
WHERE custid IN (
    SELECT custid
    FROM ORDERS
    WHERE total_amount > (SELECT AVG(total_amount) FROM ORDERS)
);
--2
SELECT P.NAME
FROM PRODUCTS P
WHERE PRICE > (SELECT AVG(P1.PRICE) FROM PRODUCTS P1);

--3
SELECT E.ENAME,E.SAL
FROM EMPLOYEES E
WHERE E.SAL > (
SELECT MAX(E.SAL) 
FROM EMPLOYEES E
INNER JOIN DEPARTMENTS D ON E.DEPTNO=D.DEPTNO
WHERE DNAME='HR');

SELECT E.ENAME,E.SAL
FROM EMPLOYEES E
WHERE E.SAL > ALL (
SELECT (E.SAL) 
FROM EMPLOYEES E
INNER JOIN DEPARTMENTS D ON E.DEPTNO=D.DEPTNO
WHERE DNAME='HR');

--4

SELECT P.NAME
FROM PRODUCTS P
WHERE P.PRODID NOT IN(
SELECT PC.PRODID 
FROM PRODUCT_CATEGORIES PC
WHERE CATID =(
SELECT CATID FROM CATEGORIES 
WHERE CNAME = 'Electronics'));




--5

SELECT E.ENAME
FROM EMPLOYEES E
WHERE E.SAL IN (
SELECT SAL FROM SALGRADES S WHERE S.GRADE=3);

--6
SELECT C.CNAME,P.NAME
FROM CUSTOMERS C
INNER JOIN ORDERS O ON C.CUSTID=O.CUSTID
INNER JOIN ORDER_ITEMS OT ON o.ordid=ot.ordid
INNER JOIN PRODUCTS P ON OT.PRODID=P.PRODID;

--7
 
 SELECT C.CNAME,C.EMAIL
 FROM CUSTOMERS C
 WHERE C.CUSTID=(
 SELECT O.CUSTID FROM ORDERS O WHERE O.STATUS='Shipped');
 
SELECT C.CNAME,C.EMAIL
FROM CUSTOMERS C
INNER JOIN ORDERS O ON C.CUSTID=O.CUSTID
WHERE O.STATUS = 'Shipped';
 
--8

SELECT E.ENAME AS EMPLEADOS ,E1.ENAME AS JEFE
FROM EMPLOYEES E
INNER JOIN EMPLOYEES E1 ON E.MGR=E1.MGR;

--9

SELECT P.NAME,C.CNAME
FROM PRODUCTS P
INNER JOIN PRODUCT_CATEGORIES PC ON P.PRODID=PC.PRODID
INNER JOIN CATEGORIES C ON PC.CATID=C.CATID;

--10

SELECT D.DNAME,E.ENAME
FROM departments D
INNER JOIN EMPLOYEES E ON D.DEPTNO=E.DEPTNO;

--11

SELECT SUM(AMOUNT) AS TOTAL_VENTAS
FROM TRANSACTIONS
GROUP BY payment_method;

--12


SELECT D.dname, AVG(E.sal) AS avg_salary
FROM DEPARTMENTS D
JOIN  EMPLOYEES E  ON D.deptno=E.deptno
GROUP BY D.dname
ORDER BY avg_salary DESC;

--13
SELECT C.CNAME,SUM(P.STOCK) AS TOTAL_STOCK
FROM PRODUCTS P
INNER JOIN PRODUCT_CATEGORIES PC ON P.PRODID = PC.PRODID
INNER JOIN CATEGORIES C ON PC.CATID=C.CATID
GROUP BY C.CNAME;


--14

SELECT COUNT(DISTINCT(CUSTID)) AS TOTAL_CLIENTES
FROM ORDERS;

--15
SELECT C.CNAME,SUM(O.TOTAL_AMOUNT) AS TOTAL_INGRESOS
FROM CUSTOMERS C
JOIN ORDERS O ON C.custid = O.custid
GROUP BY C.CNAME;

--16
SELECT E.ENAME
FROM EMPLOYEES E
WHERE E.DEPTNO=(
SELECT E1.DEPTNO 
FROM EMPLOYEES E1
WHERE E1.ENAME='John');

--17
SELECT P.NAME ,O.TOTAL_AMOUNT AS TOTAL_PEDIDOS
FROM PRODUCTS P
INNER JOIN ORDER_ITEMS OT ON P.PRODID=OT.PRODID
INNER JOIN ORDERS O ON OT.ORDID=O.ORDID
WHERE TOTAL_AMOUNT>200;

 --18
