--CREACION DE VISTA PERIMITEN DML
CREATE OR REPLACE VIEW VISTA_EMP AS
SELECT  E.ENAME, E.SAL, D.DNAME,E.DEPTNO
FROM EMP E
INNER JOIN DEPT D ON E.DEPTNO=D.DEPTNO
WHERE E.SAL>(
SELECT AVG(E1.SAL) AS SALARIO_MEDIO FROM
EMP E1
WHERE E1.DEPTNO=E.DEPTNO)
WITH CHECK OPTION CONSTRAINT VISTA_SAL_CK;
--VER MI VISTA
SELECT * FROM VISTA_EMP;

--MANIPULACION DE RESTRICCIONES ALTER TABLE

