CREATE TABLE ARTISTA(

DNI VARCHAR2(10) PRIMARY KEY,
NOMBRE VARCHAR2(20) NOT NULL,
CATEGORIA VARCHAR2(20) NOT NULL


);

 CREATE TABLE ESTILO(
 
 CODESTILO INT PRIMARY KEY,
 NOMBRE VARCHAR2(20) NOT NULL,
 DESCRIPCION VARCHAR2(50)
 
 );

CREATE TABLE OBRA (

CÓDIGO INT PRIMARY KEY,
NOMBRE VARCHAR2(30) NOT NULL,
TIPO_VALOR VARCHAR2(30),
ESTILO INT,
AUTOR VARCHAR2(30),


CONSTRAINT FK_OBRA_ESTILO FOREIGN KEY(ESTILO) REFERENCES ESTILO (CODESTILO),
CONSTRAINT FK_OBRA_AUTOR FOREIGN KEY (AUTOR) REFERENCES ARTISTA (DNI)

);

CREATE TABLE EXPONE(

COD_OBRA INT PRIMARY KEY,
MUSEO VARCHAR2(20) NOT NULL,
FECHA_INICIO DATE NOT NULL,
FECHA_FIN DATE NOT NULL

);


CREATE TABLE MUSEO(

NOMBRE VARCHAR2(20) PRIMARY KEY ,
DOMICILIO VARCHAR2(30),
CIUDAD VARCHAR2(20),
TELEFONO INT

);

INSERT INTO ARTISTA VALUES (
'88273645A','MIGUEL ZABALA','PRINCIPIANTE'
);
INSERT INTO ESTILO VALUES (
'100000',' MODERNISTA','FINALES DEL SIGLO XXI'
);
INSERT INTO OBRAS VALUES (
'10680','VUELO DEL FENIX','ESCULTURA,950','100000','88273645A'
);
INSERT INTO EXPONE VALUES (
'10680','DART','30/01/2021','30/06/2021'
);
INSERT INTO MUSEO VALUES (
'EL PRADO','RUIZ DE ALARCON,23','MADRID','913302800'
);

